### ISSUE TITLE
脚本在黑苹果下终端电池电量显示和顶栏不一致

### ISSUE THREAD

**Issue by Zeroneplus** [athlonreg/archey-osx#1]
hi，athlonreg
        非常感谢你的汉化工作，但是我在使用的过程中发现脚本在黑苹果下终端输出的电池电量显示和顶栏用Rehabman的电池驱动显示的电量不一致，我想问一下你遇到过同样的问题吗，这是黑苹果的通用毛病吗？
        然后就是你的安装命令"echo archey >> ./.bashrc #中文版"，我觉得最好还是改成"echo archey >> ~/.bashrc #中文版"（其他命令也类似），确实可能有些不太懂的用户会搞错，我第一次安装也安装失败，后来学了Linux才弄明白。

**Comment by valasco** [comment]
how to uninstall it？

**Comment by athlonreg** [comment]
> hi，athlonreg
> 非常感谢你的汉化工作，但是我在使用的过程中发现脚本在黑苹果下终端输出的电池电量显示和顶栏用Rehabman的电池驱动显示的电量不一致，我想问一下你遇到过同样的问题吗，这是黑苹果的通用毛病吗？
> 然后就是你的安装命令"echo archey >> ./.bashrc #中文版"，我觉得最好还是改成"echo archey >> ~/.bashrc #中文版"（其他命令也类似），确实可能有些不太懂的用户会搞错，我第一次安装也安装失败，后来学了Linux才弄明白。

正常的，这是苹果官方的显示策略，不用管。另外那个命令是之前在用户根目录下敲的，为了通用性我改一下吧，谢谢提醒
